version: '3.8'

services:
  ai-favs:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    env_file:
      - .env
    volumes:
      # 数据持久化
      - ./app/db/files:/code/app/db/files
      - ./app/vectorestore:/code/app/vectorestore
      - ./app/public:/code/app/public
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3 